In [151]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [152]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [154]:
df["is_male"] = (df["sex"] == "male").astype(int)
df["is_female"] = (df["sex"] == "female").astype(int)
df.drop(columns=["sex"], inplace= True)
df.head()

   age     bmi  children smoker     region      charges  is_male  is_female
0   19  27.900         0    yes  southwest  16884.92400        0          1
1   18  33.770         1     no  southeast   1725.55230        1          0
2   28  33.000         3     no  southeast   4449.46200        1          0
3   33  22.705         0     no  northwest  21984.47061        1          0
4   32  28.880         0     no  northwest   3866.85520        1          0

In [155]:
df["is_smoker"] = df["smoker"].map({"yes": 1,
                                    "no": 0})
df.drop(columns=["smoker"], inplace= True)
df.head()

,age,bmi,children,region,charges,is_male,is_female,is_smoker
0,19,27.900,0,southwest,16884.92400,0,1,1
1,18,33.770,1,southeast,1725.55230,1,0,0
2,28,33.000,3,southeast,4449.46200,1,0,0
3,33,22.705,0,northwest,21984.47061,1,0,0
4,32,28.880,0,northwest,3866.85520,1,0,0

In [156]:
regions = np.array(df["region"].unique())

In [157]:
for region in regions:
    df[region] = (df["region"] == region).astype(int)
df.drop(columns="region", inplace= True)
df.head()

,age,bmi,children,charges,is_male,is_female,is_smoker,southwest,southeast,northwest,northeast
0,19,27.900,0,16884.92400,0,1,1,1,0,0,0
1,18,33.770,1,1725.55230,1,0,0,0,1,0,0
2,28,33.000,3,4449.46200,1,0,0,0,1,0,0
3,33,22.705,0,21984.47061,1,0,0,0,0,1,0
4,32,28.880,0,3866.85520,1,0,0,0,0,1,0

In [158]:
df["age"] = df["age"] / df["age"].mean()
df["bmi"] = df["bmi"] / df["bmi"].mean()
df["children"] = df["children"] / df["children"].mean()
df["charges"] = df["charges"] / df["charges"].mean()

In [159]:
target = np.array(df["charges"])
X = np.array(df.drop(columns=["charges"]))
print(target)
print(X)

[1.27237277 0.13002995 0.33529167 ... 0.122817   0.1513098  2.1959633 ]
[[0.48460703 0.90987962 0.         ... 0.         0.         0.        ]
 [0.45910139 1.10131308 0.91331058 ... 1.         0.         0.        ]
 [0.71415772 1.07620171 2.73993174 ... 1.         0.         0.        ]
 ...
 [0.45910139 1.20175857 0.         ... 1.         0.         0.        ]
 [0.53561829 0.84139406 0.         ... 0.         0.         0.        ]
 [1.55584361 0.94803587 0.         ... 0.         1.         0.        ]]

In [160]:
weights = np.zeros(X.shape[1] + 1)
bias = np.ones((X.shape[0], 1))
X = np.hstack((bias, X))
print(X.shape)
print(weights.shape)

(1338, 11)
(11,)

In [161]:
learning_rate = 0.0000005
for i in range(0, 10000):
    h_of_x = X @ weights
    deltas = h_of_x - target
    for index in range(0, X.shape[1]):
        gradient = deltas * X[:, index]
        weights[index] = weights[index] - learning_rate * gradient.sum()

In [162]:
predictions = X @ weights
error = predictions - target
mse = error ** 2
print(mse.mean())

0.2970016384940141